### ISSUE TITLE
Making the links clickable.

### ISSUE THREAD

**Issue by raiden076** [devforth/hothost#16]
Not really an issue, but can you by any chance, make the links clickable..?
thanks..

**Comment by ivictbor** [comment]
You mean links on http monitor tab, right? So they should go to URL?

**Comment by raiden076** [comment]
exactly

**Comment by ivictbor** [comment]
Will be done! Thanks a lot for feedback, it makes sense, not sure why we did nit perform it out of the box 🙂

**Comment by raiden076** [comment]
No worries, great project by the way, helped me a lot..!

**Comment by raiden076** [comment]
And, just another small feedback, Doesn't it make sense to make the tags, more bigger and prominent, Sort of like titles, and make the urls smaller,
Just like hostname and public ip, in host monitoring?
and the Title component clickable too,

Just some thoughts.

**Comment by ivictbor** [comment]
Yep, sounds very interesting, probably you can attach some Draft, kinda in paint or any fast graphic program (just to understand sizes very roughly and positioning)

**Comment by raiden076** [comment]
Some thing like this maybe?
![image](https://user-images.githubusercontent.com/40303218/205384709-d958e061-3819-457c-aaf2-c9943b9efafa.png)
But Maybe shift the uptime, just a bit more right..

**Comment by ivictbor** [comment]
> Some thing like this maybe? ![image](https://user-images.githubusercontent.com/40303218/205384709-d958e061-3819-457c-aaf2-c9943b9efafa.png) But Maybe shift the uptime, just a bit more right.. And Both the title and the url is clickable..

Thanks, just to clarify, what happens on title click? 

BTW We also plan to add edit dialog to http host soon, at least it will be available under 3 dots menu.

**Comment by raiden076** [comment]
Well Any ideas, other than The url itself?
I don't have any Based on What you guys have currently implemented..
If you plan to include any history of down time and uptime in future, maybe that..?
Man I really need to learn web dev soon, wish i could contribute in more direct ways.
It's a cool project.

**Comment by raiden076** [comment]
oh and other thing, why do we need the up/downtime label in every row, 
![image](https://user-images.githubusercontent.com/40303218/205386467-63760ac7-2ca0-4d91-b36c-54e050485096.png)
wouldn't it make sense to just add it on top, so then it would look a lot less cluttered, right?

**Comment by IhorStorozhok** [comment]
> Not really an issue, but can you by any chance, make the links clickable..? thanks..

Thanks for your feedback, I already made the links clickable, that was a great idea.
As for other features, unfortunately we can't spend a lot of time on the UI right now, so you can create your own pull request if you wish.
Current version of hothost-web image : hothost-web:1.2.18 .
