### ISSUE TITLE
Hostname should be updated

### ISSUE THREAD

**Issue by smokedsalmonbagel** [devforth/hothost#27]
If a hostname changes the changes are not reflected in the app.  It looks like it is sent each time but maybe it is not being updated on the server app?

**Comment by ivictbor** [comment]
For now hostname is captured only on agent start. If you are using docker agent please restart agent using 


```
docker restart hothost-agent 
```

On the maxhine with agent. Otherwise restart script process using kill/etc

**Comment by smokedsalmonbagel** [comment]
Ahh - so it does.  Perfect.  I run getinfo.sh as a supervisord service so `supervisorctl restart all` worked.  Thanks.
